#ifndef TECTONIC_TEXTUREDEFS_H
#define TECTONIC_TEXTUREDEFS_H

#define COLOR_TEXTURE_UNIT              GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX        0
#define SHADOW_TEXTURE_UNIT             GL_TEXTURE1
#define SHADOW_TEXTURE_UNIT_INDEX       1
#define NORMAL_TEXTURE_UNIT             GL_TEXTURE2
#define NORMAL_TEXTURE_UNIT_INDEX       2
#define RANDOM_TEXTURE_UNIT             GL_TEXTURE3
#define RANDOM_TEXTURE_UNIT_INDEX       3
#define DISPLACEMENT_TEXTURE_UNIT       GL_TEXTURE4
#define DISPLACEMENT_TEXTURE_UNIT_INDEX 4
#define MOTION_TEXTURE_UNIT             GL_TEXTURE5
#define MOTION_TEXTURE_UNIT_INDEX       5
#define SPECULAR_EXPONENT_UNIT          GL_TEXTURE6
#define SPECULAR_EXPONENT_UNIT_INDEX    6
#define CASCADE_SHADOW_TEXTURE_UNIT0        SHADOW_TEXTURE_UNIT
#define CASCADE_SHADOW_TEXTURE_UNIT0_INDEX  SHADOW_TEXTURE_UNIT_INDEX
#define CASCADE_SHADOW_TEXTURE_UNIT1        GL_TEXTURE7
#define CASCADE_SHADOW_TEXTURE_UNIT1_INDEX  6
#define CASCADE_SHADOW_TEXTURE_UNIT2        GL_TEXTURE8
#define CASCADE_SHADOW_TEXTURE_UNIT2_INDEX  8
#define SHADOW_CUBE_MAP_TEXTURE_UNIT        GL_TEXTURE9
#define SHADOW_CUBE_MAP_TEXTURE_UNIT_INDEX  9
#define SKYBOX_CUBE_MAP_TEXTURE_UNIT        GL_TEXTURE10
#define SKYBOX_CUBE_MAP_TEXTURE_UNIT_INDEX  10

#endif //TECTONIC_TEXTUREDEFS_H
