#ifndef TECTONIC_CONFIG_DEFS_H
#define TECTONIC_CONFIG_DEFS_H

#define SHADOW_WIDTH  2000
#define SHADOW_HEIGHT 2000
#define SHADOW_FOV    45.0
#define SHADOW_NEAR   0.1
#define SHADOW_FAR    150.0

#endif //TECTONIC_CONFIG_DEFS_H
